version: 2

models:
  - name: validation
    description: this is my order table applying testing
    columns:
      - name: id
        tests:
          - not_null
        description: checking id is not null

      - name: location
        tests:
          - accepted_values:
              values: ['Mumbai',
                      'Gurgram',
                      'Noida',
                      'USA']

  - name: stg_location_salary
    columns:
      - name: total_salary
        tests:
          - positive_value
        description: using macro here
      
